CREATE DATABASE JamTanEduSuiteDB;

USE JamTanEduSuiteDB;

CREATE TABLE Student (
StudentID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
StudentFirstName VARCHAR(60) NOT NULL,
StudentLastName VARCHAR(60) NOT NULL,
StudentBirthDate DATE NOT NULL,
StudentTown VARCHAR(60) NOT NULL,
StudentGender ENUM("Male", "Female"),
StudentSchool_Year TINYINT UNSIGNED NOT NULL DEFAULT 0,
StudentPicture VARCHAR(255) NOT NULL DEFAULT 'default',
Contact1 VARCHAR(8) NOT NULL,
Contact2 VARCHAR(8),
FatherFirst_Name VARCHAR(60) NOT NULL,
FatherLast_Name VARCHAR(60) NOT NULL,
MotherFirst_Name VARCHAR(60) NOT NULL,
MotherLast_Name VARCHAR(60) NOT NULL
) ENGINE = INNODB;

CREATE TABLE ProgramCategory (
CategoryID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
CategoryName VARCHAR(100) NOT NULL 
);

CREATE TABLE Program (
ProgramID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
ProgramName VARCHAR(100) NOT NULL,
MinAge INTEGER UNSIGNED,
MaxAge INTEGER UNSIGNED,
CategoryID INTEGER,
FOREIGN KEY (CategoryID) REFERENCES ProgramCategory(CategoryID)
);

CREATE TABLE Enrollment (
EnrollmentID INTEGER NOT NULL PRIMARY KEY (StudentID, ProgramID),
EnrollmentDate DATE NOT NULL DEFAULT (CURRENT_DATE),
EnrollmentStatus TINYINT UNSIGNED NOT NULL DEFAULT 0,
StudentID INTEGER NOT NULL,
ProgramID INTEGER NOT NULL,
FOREIGN KEY (StudentID) REFERENCES Student(StudentID),
FOREIGN KEY (ProgramID) REFERENCES Program(ProgramID)
);

CREATE TABLE StudentAttendance (
AttendanceID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
AttendanceDate DATE NOT NULL DEFAULT CURRENT_DATE,
Attendance ENUM("Absent", "Present") NOT NULL,
Reason VARCHAR(255),
EnrollmentID INTEGER NOT NULL,
FOREIGN KEY(EnrollmentID) REFERENCES Enrollment(EnrollmentID)
);

CREATE TABLE AssessmentType (
TypeID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
TypeName VARCHAR(100) NOT NULL
);

CREATE TABLE Assessment (
AssessmentID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
AssessmentName VARCHAR(100) NOT NULL,
AssessmentPublishDate DATE NOT NULL DEFAULT CURRENT_DATE,
AssessmentStartDate DATE,
AssessmentDueDate DATE NOT NULL,
MaxGrade INTEGER UNSIGNED NOT NULL,
PassGrade INTEGER UNSIGNED NOT NULL,
TypeID INTEGER NOT NULL,
ProgramID INTEGER NOT NULL,
FOREIGN KEY (ProgramID) REFERENCES Program(ProgramID),
FOREIGN KEY (TypeID) REFERENCES AssessmentType(TypeID)
);

CREATE TABLE Grade (
GradeID INTEGER NOT NULL PRIMARY KEY (AssessmentID, EnrollmentID),
Grade INTEGER UNSIGNED NOT NULL,
Pass ENUM("Fail", "Pass") NOT NULL,
GradeDate DATE NOT NULL DEFAULT CURRENT_DATE,
Feedback VARCHAR(500),
AssessmentID INTEGER NOT NULL,
EnrollmentID INTEGER NOT NULL,
FOREIGN KEY (AssessmentID) REFERENCES Assessment(AssessmentID),
FOREIGN KEY (EnrollmentID) REFERENCES Enrollment(EnrollmentID)
);

CREATE TABLE Staff (
StaffID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
StaffFirstName VARCHAR(60) NOT NULL,
StaffLastName VARCHAR(60) NOT NULL,
StaffTitle ENUM("Mr", "Mrs", "Ms") NOT NULL,
Town VARCHAR(100) NOT NULL,
StaffContact1 VARCHAR(8) NOT NULL,
StaffContact2 VARCHAR(8),
Email VARCHAR(255),
StaffPicture VARCHAR(255) NOT NULL DEFAULT "default.jpg",
StaffPassword VARCHAR(255) NOT NULL,
StaffAccessLevel ENUM("Teacher", "Administrator")
);

CREATE TABLE Assignment (
AssignmentID INTEGER NOT NULL PRIMARY KEY (StaffID, ProgramID),
AssignmentDate DATE NOT NULL DEFAULT CURRENT_DATE,
AssignmentStatus TINYINT UNSIGNED NOT NULL DEFAULT 0,
StaffID INTEGER NOT NULL,
ProgramID INTEGER NOT NULL,
FOREIGN KEY (StaffID) REFERENCES Staff(StaffID),
FOREIGN KEY (ProgramID) REFERENCES Program(ProgramID)
);

CREATE TABLE StaffAttendance (
AttendanceID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
AttendanceDate DATE NOT NULL DEFAULT CURRENT_DATE,
Attendance ENUM("Absent", "Present") NOT NULL,
AssignmentID INTEGER NOT NULL,
FOREIGN KEY (AssignmentID) REFERENCES Assignment(AssignmentID) 
);
