CREATE DATABASE JamTanEduSuiteDB;

USE JamTanEduSuiteDB;

CREATE TABLE Student (
StudentID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
StudentFirstName VARCHAR(60) NOT NULL,
StudentLastName VARCHAR(60) NOT NULL,
StudentBirthDate DATE NOT NULL,
StudentTown VARCHAR(60) NOT NULL,
StudentGender ENUM("Male", "Female"),
StudentSchool_Year TINYINT UNSIGNED NOT NULL DEFAULT 0,
StudentPicture VARCHAR(255),
Contact1 VARCHAR(8) NOT NULL,
Contact2 VARCHAR(8),
FatherFirst_Name VARCHAR(60) NOT NULL,
FatherLast_Name VARCHAR(60) NOT NULL,
MotherFirst_Name VARCHAR(60) NOT NULL,
MotherLast_Name VARCHAR(60) NOT NULL
) ENGINE = INNODB;

CREATE TABLE Program (
ProgramID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
ProgramName VARCHAR(100) NOT NULL,
MinAge INTEGER UNSIGNED,
MaxAge INTEGER UNSIGNED,
ProgramType INTEGER UNSIGNED NOT NULL
);

CREATE TABLE Enrollment (
EnrollmentID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
EnrollmentDate DATE NOT NULL DEFAULT (CURRENT_DATE),
EnrollmentStatus TINYINT UNSIGNED NOT NULL DEFAULT 0,
StudentID INTEGER NOT NULL,
ProgramID INTEGER NOT NULL,
FOREIGN KEY (StudentID) REFERENCES Student(StudentID),
FOREIGN KEY (ProgramID) REFERENCES Program(ProgramID)
);

CREATE TABLE StudentAttendance (
AttendanceID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
AttendanceDate DATE NOT NULL DEFAULT CURRENT_DATE,
Attendance ENUM("Absent", "Present") NOT NULL,
Reason VARCHAR(255),
EnrollmentID INTEGER NOT NULL,
FOREIGN KEY(EnrollmentID) REFERENCES Enrollment(EnrollmentID)
);

CREATE TABLE Assessment (
AssessmentID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
AssessmentName VARCHAR(100) NOT NULL,
AssessmentPublishDate DATE NOT NULL DEFAULT CURRENT_DATE,
AssessmentStartDate DATE,
AssessmentDueDate DATE NOT NULL,
MaxGrade INTEGER UNSIGNED NOT NULL,
PassGrade INTEGER UNSIGNED NOT NULL,
AssessmentType TINYINT UNSIGNED NOT NULL,
ProgramID INTEGER NOT NULL,
FOREIGN KEY (ProgramID) REFERENCES Program(ProgramID)
);

CREATE TABLE Grade (
GradeID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
Grade INTEGER UNSIGNED NOT NULL,
Feedback VARCHAR(500),
Pass ENUM("Fail", "Pass") NOT NULL,
AssessmentID INTEGER NOT NULL,
EnrollmentID INTEGER NOT NULL,
FOREIGN KEY (AssessmentID) REFERENCES Assessment(AssessmentID),
FOREIGN KEY (EnrollmentID) REFERENCES Enrollment(EnrollmentID)
);

CREATE TABLE Staff (
StaffID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
StaffFirstName VARCHAR(60) NOT NULL,
StaffLastName VARCHAR(60) NOT NULL,
StaffTitle ENUM("Mr", "Mrs", "Ms"),
Town VARCHAR(100) NOT NULL,
StaffContact1 VARCHAR(8) NOT NULL,
StaffContact2 VARCHAR(8),
Email VARCHAR(255),
StaffPicture VARCHAR(255),
StaffPassword VARCHAR(255) NOT NULL
);

CREATE TABLE Assignment (
AssignmentID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
AssignmentDate DATE NOT NULL DEFAULT CURRENT_DATE,
AssignmentStatus TINYINT UNSIGNED NOT NULL DEFAULT 0,
StaffID INTEGER NOT NULL,
ProgramID INTEGER NOT NULL,
FOREIGN KEY (StaffID) REFERENCES Staff(StaffID),
FOREIGN KEY (ProgramID) REFERENCES Program(ProgramID)
);

CREATE TABLE StaffAttendance (
AttendanceID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
AttendanceDate DATE NOT NULL DEFAULT CURRENT_DATE,
Attendance ENUM("Present", "Absent") NOT NULL,
AssignmentID INTEGER NOT NULL,
FOREIGN KEY (AssignmentID) REFERENCES Assignment(AssignmentID) 
);
